apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprofile-db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vprofile-db
  template:
    metadata:
      labels:
        app: vprofile-db
    spec:
      containers:
        - name: vprofile-db
          image: 278607931101.dkr.ecr.eu-north-1.amazonaws.com/vprofile-db:%version%
          ports:
            - containerPort: 3306
      imagePullSecrets:
            - name: ecr-credentials
